### ISSUE TITLE
Add the installation instructions for contributing

### ISSUE THREAD

**Issue by harshraj22** [devrimcavusoglu/pybboxes#11]
https://github.com/devrimcavusoglu/pybboxes/blob/dd4598cb8feae79962f6092e73e9ccb1082cf841/tests/utils.py#L8

Add the dependency in `requirements.txt`.

**Comment by devrimcavusoglu** [comment]
For contributors, dev requirements must be used. Although the package is not missing (see [setup.py](https://github.com/devrimcavusoglu/pybboxes/blob/dd4598cb8feae79962f6092e73e9ccb1082cf841/setup.py#L29)), installation instructions are missing in the readme.
