### ISSUE TITLE
Feature Request: Conversion between annotation files

### ISSUE THREAD

**Issue by devrimcavusoglu** [devrimcavusoglu/pybboxes#27]
Currently, pybboxes support box format conversion, this bounding box types usually come from a dataset each of which have associated with a particular annotation file, we can add a support to convert from one annotation file type to another.

**Comment by gauravparajuli** [comment]
Hi, I want to work on this feature.

**Comment by devrimcavusoglu** [comment]
Hi @gauravparajuli, it would be wonderful. I started with some draft, but the work is never completed as I didn't have a chance to get back to it. Let me first sketch up the abstraction and how to proceed, then be happy to hand it over to you. I will be replying here. Meanwhile, can you check [this branch](https://github.com/devrimcavusoglu/pybboxes/tree/annotation-file-support) and the changes.

**Comment by gauravparajuli** [comment]
Hey Man,

Thanks for the opportunity and I appreciate you taking time to sketch up
some abstractions for me.

I will review the changes made to your prescribed branch.

**Comment by devrimcavusoglu** [comment]
Hi @gauravparajuli, did you have a chance to check the branch ? We can take it from there and work implementation after finalizing the sketch.

**Comment by gauravparajuli** [comment]
Hi,

I just started working on it yesterday, I forked the repo and viewed the
code trying to make sense of how it works.

I will get back to you soon.

**Comment by devrimcavusoglu** [comment]
Closed by #32
